DROP TABLE IF EXISTS  CASCADE;

--Child of map, grandchild to user

CREATE TABLE {
  id PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
}
